# -*- coding: utf-8 -*-
"""Build chord-sheet.heic -- the same photograph, in the container Chrome refuses.

Why the fixture is committed rather than generated by the run: nothing on a
normal machine writes HEIC. ImageMagick reads it and cannot write it (`magick
-list format` shows HEIC as `r--`), ffmpeg has no HEIF muxer, and Chrome cannot
encode what it cannot decode. `pillow-heif` can, because its wheels bundle
libheif with the x265 encoder -- so this script needs `pip install pillow-heif`
and the e2e run does not.

Run it only to regenerate the fixture:

    python e2e/make_heic.py

The check at the end is the point. An encoder that is missing does not always
fail loudly; it can hand back a file with a different brand, and a fixture that
is quietly a JPEG would make the HEIC case in import.e2e.cjs pass while proving
nothing at all. `ftyp` at offset 4 and `heic` at offset 8 is what
`sniffImageFormat` reads, so it is what this asserts -- the same twelve bytes,
from the other side.
"""
import io
import os

from PIL import Image
import pillow_heif

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'chord-sheet.png')
OUT = os.path.join(HERE, 'chord-sheet.heic')

info = pillow_heif.libheif_info()
print('libheif:', info['libheif'], '| HEIF encoder:', info['HEIF'] or 'NONE')
if not info['HEIF']:
    raise SystemExit('this pillow-heif has no HEIF encoder; nothing to do')

pillow_heif.register_heif_opener()
image = Image.open(SRC).convert('RGB')
print('source:', SRC, image.size)

# Quality 90 keeps it above the reader's own compression floor: the notice in
# `_minBytesPerPixel` fires below 0.08 bytes per pixel, and this lands at 0.092.
# A harder squeeze would make the run fail on a low-resolution warning rather
# than on anything to do with the container.
image.save(OUT, format='HEIF', quality=90)

data = io.open(OUT, 'rb').read()
brand = data[8:12]
print('wrote', OUT, len(data), 'bytes', '| ftyp brand:', brand)
print('bytes per pixel:', round(len(data) / (image.size[0] * image.size[1]), 4))
assert data[4:8] == b'ftyp', 'no ISO base-media header; this is not HEIC'
assert brand in (b'heic', b'heix', b'hevc', b'hevx'), (
    'brand %r is not one sniffImageFormat calls heic' % (brand,))
print('OK: sniffImageFormat would call this heic')
